apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus-1
  name: girus-1
spec:
  containers:
  - image: nginx
    name: girus-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
